import test from 'node:test'
import assert from 'node:assert/strict'
import {chromium} from '@playwright/test'
import {executeDetailRemoval} from './pdd-detail-remove.mjs'
const a='https://pfs.pinduoduo.com/a.png',b='https://pfs.pinduoduo.com/b.png',plan={scope:'pdd-tshirt-detail-remove-v1',productCode:'REMOVE-TEST',beforeUrls:[a,b],removeUrl:a}
let browser
test.before(async()=>browser=await chromium.launch({headless:true}));test.after(async()=>browser.close())
async function pageFor(){const p=await browser.newPage();await p.route('**/*',r=>r.request().url().endsWith('.png')?r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1sAAAAASUVORK5CYII=','base64')}):r.fulfill({contentType:'text/html; charset=utf-8',body:`<meta charset="utf-8"><div>女装/女士精品 &gt; T恤 &gt; T恤</div><div data-testid="beast-core-form-item"><label>商品货号</label><input value="REMOVE-TEST"></div><div class="quick-decoration-container-v2"><div class="quick_decoration_v2_sortableWrapper__fixture">已上传<span id="count">2</span>/50张<input type="file" multiple accept="image/jpeg,image/png" data-tracking-click-viewid="detail_img_localfile_upload">${[a,b].map((src,i)=>`<div class="quick_decoration_v2_remarkImage__fixture"><img src="${src}" data-tracking-click-viewid="el_preview_business_details"><span class="ImageWithRemark_v2_remark__fixture">${i+1}</span><button data-testid="beast-core-icon-close" onclick="this.parentElement.remove();const cards=document.querySelectorAll('[class*=remarkImage]');count.textContent=cards.length;cards.forEach((c,i)=>c.querySelector('span').textContent=i+1)">删除</button></div>`).join('')}</div></div>`}));await p.goto('https://mms.pinduoduo.com/goods/goods_add/index?type=add');return p}
test('preflight unchanged, exact URL removal keeps remaining image and position',async()=>{const p=await pageFor();try{assert.equal((await executeDetailRemoval(p,plan)).before.count,2);assert.equal(await p.locator('#count').textContent(),'2');const r=await executeDetailRemoval(p,plan,{dryRun:false});assert.equal(r.status,'detail_removal_subset_verified');assert.equal(r.observed.images[0].src,b);assert.equal(r.observed.images[0].position,1)}finally{await p.close()}})
test('changed baseline rejects without deleting any image',async()=>{const p=await pageFor();try{await assert.rejects(()=>executeDetailRemoval(p,{...plan,beforeUrls:[b,a]},{dryRun:false}),/BASELINE_MISMATCH/);assert.equal(await p.locator('#count').textContent(),'2')}finally{await p.close()}})
