import {useMemo,useState} from 'react'
import {boardShoesProfile} from './category-profile'
import {buildVariantMatrix,compileListingDraft,createListingDraft,createStarterDraft,regenerateVariantSkus,splitValues,validateListingDraft,type ListingDraft} from './listing-draft'
import {uploadLocalAssets,type LocalAsset} from './local-assets'
import {pasteVariantTable} from './variant-bulk'
import {parseListingSheet,readSpreadsheet} from './spreadsheet-import'
import DataBackup from './DataBackup'
import {downloadImportTemplate} from './import-template'
import './live-workbench.css'

const STORAGE_KEY='ecom-listing-draft.pdd-board-shoes.v2'
const TEMPLATE_KEY='ecom-listing-templates.pdd-board-shoes.v1'
type Template={id:string;title:string;draft:ListingDraft}

function load():ListingDraft{try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)??'null');if(value?.profileId===boardShoesProfile.id)return value}catch{}return createListingDraft(boardShoesProfile)}
function loadTemplates():Template[]{try{const value=JSON.parse(localStorage.getItem(TEMPLATE_KEY)??'[]');return Array.isArray(value)?value:[]}catch{return []}}
async function liveRequest(path:string,body:unknown={}){const response=await fetch('/api/live/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error('本机后台未连接，请先启动工作台')}if(!response.ok)throw new Error(data.error??'本机操作失败');return data}

export default function CategoryWorkbench(){
 const [draft,setDraft]=useState<ListingDraft>(load),[showIssues,setShowIssues]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const [pasteText,setPasteText]=useState(''),[templates,setTemplates]=useState<Template[]>(loadTemplates),[templateId,setTemplateId]=useState(''),[templateTitle,setTemplateTitle]=useState('')
 const issues=useMemo(()=>validateListingDraft(draft),[draft]),blocking=issues.filter(item=>item.kind==='blocking')
 const patch=(change:Partial<ListingDraft>)=>setDraft(current=>{const next={...current,...change,sample:change.sample??(Object.keys(change).some(key=>!['variants','mainImages','detailImages','colorImages'].includes(key))?false:current.sample)};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next})
 const replace=(next:ListingDraft)=>{setDraft(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setShowIssues(false)}
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn()}catch(error){setMessage(error instanceof Error?error.message:'操作失败')}finally{setBusy(false)}}
 const upload=async(files:FileList|null,done:(assets:LocalAsset[])=>void,limit=10)=>{if(!files?.length)return;await act(async()=>done(await uploadLocalAssets(files,liveRequest,limit)))}
 const saveTemplates=(next:Template[])=>{setTemplates(next);localStorage.setItem(TEMPLATE_KEY,JSON.stringify(next))}
 const newCode=async()=>((await liveRequest('next-product-code')) as {productCode:string}).productCode
 const loadStarter=()=>act(async()=>{const identity=await liveRequest('next-product-code') as {productCode:string};const assets=await liveRequest('test-assets') as {main:LocalAsset[];detail:LocalAsset[];sku:LocalAsset};replace(createStarterDraft(boardShoesProfile,identity,assets));setMessage('已载入完整演示资料。价格、库存、属性和图片都只是示例，不能直接用于上架。')})
 const importSheet=(file?:File)=>{if(!file)return;void act(async()=>{const parsed=parseListingSheet(await readSpreadsheet(file),Object.fromEntries(boardShoesProfile.attributeFields.map(field=>[field.key,field.label]))),productCode=parsed.productCode||draft.productCode||await newCode(),colors=[...new Set(parsed.rows.map(row=>row.color))].join(','),sizes=[...new Set(parsed.rows.map(row=>row.size))].join(','),base={...draft,productCode,title:parsed.title||draft.title,brand:parsed.brand||draft.brand,attributes:{...draft.attributes,...parsed.attributes},colors,sizes,sample:false};base.variants=regenerateVariantSkus(base,productCode).map(variant=>{const row=parsed.rows.find(item=>item.color===variant.color&&item.size===variant.size);return row?{...variant,groupPrice:row.groupPrice,singlePrice:row.singlePrice,stock:row.stock}:variant});replace(base);setMessage(`已从 ${file.name} 导入 ${parsed.rows.length} 行规格。图片和未提供字段保持原值，请检查后使用。`)})}
 const download=()=>{const blob=new Blob([JSON.stringify(compileListingDraft(draft),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${draft.productCode||'board-shoes'}-listing-draft.json`;a.click();URL.revokeObjectURL(url)}
 const pictureList=(title:string,key:'mainImages'|'detailImages')=><div className="category-assets"><label>{title}<input type="file" multiple accept="image/png,image/jpeg" disabled={busy} onChange={event=>{void upload(event.target.files,assets=>patch({[key]:[...draft[key],...assets]}));event.target.value='' }}/></label>{draft[key].map((asset,index)=><div className="category-asset" key={`${asset.path}-${index}`}>{asset.preview&&<img src={asset.preview} alt=""/>}<span>{index+1}. {asset.name}</span><button type="button" onClick={()=>patch({[key]:draft[key].filter((_,i)=>i!==index)})}>移除</button></div>)}</div>

 return <main className="live-workbench category-workbench">
  <nav className="category-nav" aria-label="工作台切换"><a href="/">女装 T 恤稳定工作台</a><span>板鞋实验工作台</span></nav>
  <header className="live-top"><div><span className="live-eyebrow">类目 Profile 驱动 · Experimental</span><h1>{boardShoesProfile.displayName}上新资料工作台</h1><p>录入一次商品事实，生成规格和素材包；真实页面合同验证后接入统一执行核心。</p></div><span className="live-badge">尚未启用自动填表</span></header>
  <div className="reuse-warning"><strong>页面结构已取证，自动填表仍关闭</strong><p>已确认类目 ID、字段标签、颜色、童鞋尺码、尺码表和规格矩阵。属性下拉选项、联动规则及真实写入回读仍需核对，当前页面不会猜测并执行写入。</p></div>
  <section className="live-card starter-guide"><h2>首次使用：载入完整初始示例</h2><p>示例包含基础资料、鞋类属性、2 色 × 6 鞋码、价格库存及测试图片。载入后请逐项换成自己的商品事实。</p><button type="button" disabled={busy} onClick={()=>void loadStarter()}>载入完整初始示例</button>{draft.sample&&<p className="live-warning">当前是演示资料，不可直接用于销售。</p>}</section>
  <section className="live-card"><h2>从 Excel/WPS 导入整款商品</h2><p>支持 .xlsx、.csv、.tsv。每行代表一个颜色＋鞋码组合；必须包含颜色、鞋码、拼单价、单买价和库存。可附带商品货号、商品标题、品牌及鞋类属性列。</p><div className="live-actions"><button type="button" onClick={()=>downloadImportTemplate('footwear',boardShoesProfile.attributeFields.map(field=>field.label))}>下载板鞋导入模板</button><label className="live-file">选择商品表格<input type="file" accept=".xlsx,.csv,.tsv" disabled={busy} onChange={event=>{importSheet(event.target.files?.[0]);event.target.value=''}}/></label></div></section>
  <section className="live-card"><h2>商品模板</h2><p>模板保存在本机浏览器中，可复用属性、颜色鞋码、价格库存和图片；套用时自动生成新货号和新 SKU。</p><div className="entry-fields"><label>选择模板<select value={templateId} onChange={event=>{setTemplateId(event.target.value);setTemplateTitle(templates.find(item=>item.id===event.target.value)?.title??'')}}><option value="">请选择模板</option>{templates.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>模板标题<input value={templateTitle} onChange={event=>setTemplateTitle(event.target.value)} placeholder="例如：春季低帮基础款"/></label></div><div className="live-actions"><button type="button" disabled={!templateTitle.trim()} onClick={()=>{const item={id:crypto.randomUUID(),title:templateTitle.trim(),draft:structuredClone(draft)};saveTemplates([...templates,item]);setTemplateId(item.id);setMessage('模板已保存在本机。')}}>另存为新模板</button><button type="button" disabled={!templateId} onClick={()=>void act(async()=>{const item=templates.find(value=>value.id===templateId);if(!item)throw new Error('请选择模板');const next=structuredClone(item.draft);next.productCode=await newCode();next.variants=regenerateVariantSkus(next,next.productCode);replace(next);setMessage('模板已套用，并生成新货号和新 SKU；请核实价格、库存和图片。')})}>套用为新商品</button><button type="button" disabled={!templateId} onClick={()=>{saveTemplates(templates.filter(item=>item.id!==templateId));setTemplateId('');setTemplateTitle('');setMessage('模板已删除，当前商品不受影响。')}}>删除所选模板</button></div></section>
  <section className="live-card"><h2>1. 基础资料</h2><p>{boardShoesProfile.categoryPath}</p><div className="entry-fields"><label>商品货号（款式编号）<input value={draft.productCode} onChange={event=>{const productCode=event.target.value;patch({productCode,variants:regenerateVariantSkus(draft,productCode)})}}/></label>{([['title','商品标题'],['brand','品牌']] as const).map(([key,label])=><label key={key}>{label}<input value={draft[key]} onChange={event=>patch({[key]:event.target.value})}/></label>)}</div></section>
  <section className="live-card"><h2>2. 板鞋属性</h2><p>字段标签已经按童鞋板鞋页面整理；下拉字段先记录商品事实，取得平台选项后再绑定成选择框。</p><div className="entry-fields">{boardShoesProfile.attributeFields.map(field=><label key={field.key}>{field.label}{field.required?' *':''}<input value={draft.attributes[field.key]??''} onChange={event=>patch({attributes:{...draft.attributes,[field.key]:event.target.value}})}/><small>{field.evidence==='unverified'?'字段已确认，下拉选项待补':'字段及输入方式已确认'}</small></label>)}</div></section>
  <section className="live-card"><h2>3. 颜色、鞋码、价格和库存</h2><div className="entry-fields"><label>颜色（逗号分隔）<input value={draft.colors} onChange={event=>patch({colors:event.target.value})}/></label><label>鞋码（逗号分隔）<input value={draft.sizes} onChange={event=>patch({sizes:event.target.value})}/></label><label>发货时效<select value={draft.shippingPromise} onChange={event=>patch({shippingPromise:event.target.value as ListingDraft['shippingPromise']})}><option value="48h_handover">48 小时内发货及揽收</option><option value="24h_handover">24 小时内发货及揽收</option></select></label></div><button type="button" onClick={()=>{try{patch({variants:buildVariantMatrix(draft)})}catch(error){setMessage((error as Error).message)}}}>生成 / 更新规格矩阵</button>
   <details><summary>从 Excel/WPS 粘贴价格库存</summary><p>复制包含表头的数据，按“颜色＋鞋码”匹配，不要求行顺序一致。</p><textarea aria-label="粘贴板鞋价格库存" value={pasteText} onChange={event=>setPasteText(event.target.value)} placeholder={'颜色\t鞋码\t拼单价\t单买价\t库存\n黑白\t35\t99\t109\t20'}/><button type="button" onClick={()=>{try{const result=pasteVariantTable(draft.variants,pasteText);patch({variants:result.variants});setPasteText('');setMessage(`已从表格写入 ${result.changes} 个价格库存值。`)}catch(error){setMessage((error as Error).message)}}}>检查并应用表格</button></details>
   {draft.variants.length>0&&<div className="entry-scroll"><table><thead><tr><th>颜色 / 鞋码</th><th>规格编码</th><th>拼单价</th><th>单买价</th><th>库存</th><th>启用</th></tr></thead><tbody>{draft.variants.map((row,index)=><tr key={`${row.color}-${row.size}`}><td>{row.color} / {row.size}</td>{(['merchantSku','groupPrice','singlePrice','stock'] as const).map(key=><td key={key}><input aria-label={`${row.color}${row.size}${key}`} value={row[key]} onChange={event=>patch({variants:draft.variants.map((item,i)=>i===index?{...item,[key]:event.target.value}:item)})}/></td>)}<td><input aria-label={`${row.color}${row.size}启用`} type="checkbox" checked={row.enabled} onChange={event=>patch({variants:draft.variants.map((item,i)=>i===index?{...item,enabled:event.target.checked}:item)})}/></td></tr>)}</tbody></table></div>}
  </section>
  <section className="live-card"><h2>4. 商品图片</h2><p>直接选择 JPG/PNG 图片，文件会复制到本机工作台数据目录。主图按已观察的平台规则限制为最多 10 张、单张不超过 3MB；尺寸和内容仍会在执行前复核。</p>{pictureList('主图（最多 10 张）','mainImages')}{pictureList('详情图（最多 10 张）','detailImages')}<div className="entry-fields">{splitValues(draft.colors).map(color=><div className="category-assets" key={color}><label>{color}规格图<input aria-label={`选择${color}规格图`} type="file" accept="image/png,image/jpeg" disabled={busy} onChange={event=>{void upload(event.target.files,assets=>patch({colorImages:{...draft.colorImages,[color]:assets[0]}}),1);event.target.value='' }}/></label>{draft.colorImages[color]&&<div className="category-asset">{draft.colorImages[color].preview&&<img src={draft.colorImages[color].preview} alt=""/>}<span>{draft.colorImages[color].name}</span><button type="button" onClick={()=>{const next={...draft.colorImages};delete next[color];patch({colorImages:next})}}>移除</button></div>}</div>)}</div></section>
  <section className="live-card"><h2>5. 检查与导出</h2><p>导出的统一草稿可供后续 Adapter 使用；自动执行保持关闭，直到板鞋页面合同完成真实验证。</p><div className="live-actions"><button type="button" onClick={()=>setShowIssues(true)}>检查全部资料</button><button type="button" className="live-primary" disabled={blocking.length>0} onClick={download}>导出统一商品草稿 JSON</button></div>{showIssues&&(issues.length?<ul className="category-issues">{issues.map((issue,index)=><li className={issue.kind} key={`${issue.field}-${index}`}><b>{issue.kind==='blocking'?'需修改':'待实页确认'}</b>{issue.message}</li>)}</ul>:<p>本地资料检查通过；自动填表仍需完成平台字段取证。</p>)}</section>
  <section className="live-card"><DataBackup storageKeys={[STORAGE_KEY,TEMPLATE_KEY]}/></section>
  {message&&<p role="status" className="live-warning">{message}</p>}
  <footer>共用：商品身份、动态属性、两维规格、SKU、价格库存、图片、物流与审核；差异由类目 Profile 和平台页面合同声明。</footer>
 </main>
}
