import {getCategoryProfile,type CategoryProfile} from './category-profile'

export type DraftVariant={color:string;size:string;merchantSku:string;groupPrice:string;singlePrice:string;stock:string;enabled:boolean}
export type ListingDraft={profileId:string;productCode:string;title:string;brand:string;attributes:Record<string,string>;colors:string;sizes:string;variants:DraftVariant[];mainImages:string[];detailImages:string[];colorImages:Record<string,string>;shippingPromise:'24h_handover'|'48h_handover'}
export type DraftIssue={field:string;message:string;kind:'blocking'|'verification'}

export const splitValues=(value:string)=>value.split(/[,，\n]/).map(item=>item.trim()).filter(Boolean)
const codePart=(value:string,fallback:string)=>value.normalize('NFKC').toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'')||fallback
export function createListingDraft(profile:CategoryProfile):ListingDraft{return {profileId:profile.id,productCode:'',title:'',brand:'',attributes:Object.fromEntries(profile.attributeFields.map(field=>[field.key,''])),colors:profile.defaults.colors,sizes:profile.defaults.sizes,variants:[],mainImages:[],detailImages:[],colorImages:{},shippingPromise:'48h_handover'}}
export function buildVariantMatrix(draft:ListingDraft):DraftVariant[]{const colors=splitValues(draft.colors),sizes=splitValues(draft.sizes);if(!colors.length||!sizes.length)throw new Error('请先填写两个规格维度');if(new Set(colors).size!==colors.length||new Set(sizes).size!==sizes.length)throw new Error('颜色或尺码存在重复');if(colors.length*sizes.length>80)throw new Error('单款最多生成 80 个规格组合');return colors.flatMap((color,colorIndex)=>sizes.map(size=>{const old=draft.variants.find(row=>row.color===color&&row.size===size);return old??{color,size,merchantSku:`${codePart(draft.productCode,'ITEM')}-C${String(colorIndex+1).padStart(2,'0')}-${codePart(size,'SIZE')}`,groupPrice:'',singlePrice:'',stock:'',enabled:true}}))}
export function validateListingDraft(draft:ListingDraft):DraftIssue[]{const profile=getCategoryProfile(draft.profileId),issues:DraftIssue[]=[],block=(field:string,message:string)=>issues.push({field,message,kind:'blocking'});if(!draft.productCode.trim())block('productCode','请填写商品货号（款式编号）');if(!draft.title.trim())block('title','请填写商品标题');if(!draft.brand.trim())block('brand','请填写品牌或平台对应的无品牌选项');for(const field of profile.attributeFields){if(field.required&&!draft.attributes[field.key]?.trim())block(`attributes.${field.key}`,`请填写${field.label}`);if(field.evidence==='unverified'&&draft.attributes[field.key]?.trim())issues.push({field:`attributes.${field.key}`,message:`${field.label}的控件和平台选项仍待真实页面核对`,kind:'verification'})}let expected:DraftVariant[]=[];try{expected=buildVariantMatrix(draft)}catch(error){block('variants',(error as Error).message)}if(expected.length!==draft.variants.length)block('variants','规格维度已修改，请重新生成规格矩阵');const codes=new Set<string>();for(const row of draft.variants){if(!row.merchantSku||codes.has(row.merchantSku))block('variants',`${row.color}/${row.size} 的规格编码为空或重复`);codes.add(row.merchantSku);if(!/^\d+(\.\d{1,2})?$/.test(row.groupPrice)||Number(row.groupPrice)<=0)block('variants',`${row.color}/${row.size} 的拼单价无效`);if(!/^\d+(\.\d{1,2})?$/.test(row.singlePrice)||Number(row.singlePrice)<Number(row.groupPrice))block('variants',`${row.color}/${row.size} 的单买价无效`);if(!/^\d+$/.test(row.stock))block('variants',`${row.color}/${row.size} 的库存必须是非负整数`)}if(!draft.mainImages.length)block('mainImages','至少登记一张主图');for(const color of splitValues(draft.colors))if(!draft.colorImages[color])block('colorImages',`缺少${color}的规格图`);return issues}
export function compileListingDraft(draft:ListingDraft){const profile=getCategoryProfile(draft.profileId),issues=validateListingDraft(draft);return {schemaVersion:'0.2-draft',profile:{id:profile.id,categoryKey:profile.categoryKey,categoryPath:profile.categoryPath,status:profile.status},product:{productCode:draft.productCode,title:draft.title,brand:draft.brand,attributes:draft.attributes},variants:draft.variants,assets:{main:draft.mainImages,detail:draft.detailImages,byColor:draft.colorImages},listing:{platform:profile.platform,shippingPromise:draft.shippingPromise},validation:{blocking:issues.filter(item=>item.kind==='blocking'),verification:issues.filter(item=>item.kind==='verification')},execution:{enabled:false,reason:'类目字段与控件尚未完成真实页面取证和回读验证'}}}
