import {starterProduct} from './starter-product'
import TablePaste from './TablePaste'
import {attributeChoices,changeAttribute,attributeCatalog} from './attribute-choices'
import type {ProductTemplate} from './product-templates'
import {measurementField,sizeFields,sizeUnit,type SizeKind,type SizeField,type SizeTemplate,validateSizeTemplate} from './size-fields'
import {useEffect,useState} from 'react'
import {attributeLabels,collectFormIssues,blankForm,copyAsNewProduct,rebuildRows,regenerateSkuCodes,reuseConfirmed,applySizeTemplate,applyProductTemplate,switchSizeKind,updateForm,setReuseCheck,splitLabels,type FormData,type Picture} from './mvp-form'
type Props={disabled:boolean;onDirty:()=>void;onLoaded:()=>void;request:(path:string,body?:unknown)=>Promise<any>}
export default function ProductEntry({disabled,onDirty,onLoaded,request}:Props){
 const [form,setForm]=useState<FormData>(()=>{try{const saved=JSON.parse(localStorage.getItem('mvp-entry-v1')??'null');if(saved?.id&&saved.attributes&&Array.isArray(saved.rows))return {...saved,confirmed:false}}catch{}return blankForm(crypto.randomUUID())}),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[settings,setSettings]=useState<{shopName:string;mallId:string;templateName:string;groups:string[]}|null>(null),[defaults,setDefaults]=useState<{brand:string;attributes:Record<string,string>}|null>(null),[loadedForm,setLoadedForm]=useState<FormData|null>(null)
 const [messageFailed,setMessageFailed]=useState(false)
 const [showIssues,setShowIssues]=useState(false)
 const issues=showIssues?[...collectFormIssues(form),...(!settings?[{field:'shop',message:'请先填写并保存店铺与运费配置'}]:[])]:[]
 function focusIssue(field:string){const target=[...document.querySelectorAll<HTMLElement>('[data-field]')].find(e=>e.dataset.field===field);let ancestor=target?.parentElement;while(ancestor){if(ancestor instanceof HTMLDetailsElement)ancestor.open=true;ancestor=ancestor.parentElement}target?.scrollIntoView?.({block:'center',behavior:'smooth'});if(target instanceof HTMLInputElement&&target.type==='file'&&!target.disabled){target.click();return}(target?.matches('input,select,textarea')?target:target?.querySelector<HTMLElement>('input,select,textarea,button'))?.focus()}
 const [undoForm,setUndoForm]=useState<FormData|null>(null),[deleteTarget,setDeleteTarget]=useState<{kind:'product'|'size';id:string;name:string}|null>(null)
 function replaceForm(next:FormData){setUndoForm(structuredClone(form));setForm({...next,confirmed:false});onDirty()}
 async function saveSizeTemplate(update=false){const template=validateSizeTemplate({id:update?templateId:crypto.randomUUID(),name:templateName.trim(),fields:selectedFields,kind:sizeKind,rangeFields:form.rangeFields??[],measurements:Object.fromEntries(splitLabels(form.sizes).map(size=>[size,form.measurements[size]??{}]))});const d=await request('size-templates',{template,action:update?'update':'create'});setTemplates(d.templates);setTemplateId(template.id);setTemplateName(template.name);setMessage(update?'所选尺码模板已更新。':'尺码模板已另存到本机。')}
 const [productTemplates,setProductTemplates]=useState<ProductTemplate[]>([]),[productTemplateId,setProductTemplateId]=useState(''),[productTemplateTitle,setProductTemplateTitle]=useState('')
 useEffect(()=>{request('product-templates').then(d=>setProductTemplates(d.templates)).catch(e=>setMessage(e.message))},[request])
 const [templates,setTemplates]=useState<SizeTemplate[]>([]),[templateId,setTemplateId]=useState(''),[templateName,setTemplateName]=useState('')
 useEffect(()=>{request('size-templates').then(d=>setTemplates(d.templates)).catch(e=>setMessage(e.message))},[request])
 function measurementInput(size:string,k:SizeField,bound:'min'|'max'|'value'='value'){
 const key=measurementField(size,k,bound),error=issues.find(i=>i.field===key),id='error-'+encodeURIComponent(key),range=bound!=='value',index=bound==='max'?1:0
 const value=range?(form.measurements[size]?.[k]??'').split('-')[index]??'':form.measurements[size]?.[k]??''
 return <div key={bound} className="measurement-cell"><input data-field={key} aria-label={`${size} ${sizeFields[k].label}${bound==='min'?'下限':bound==='max'?'上限':''}`} aria-invalid={!!error} aria-describedby={error?id:undefined} placeholder={range?(bound==='min'?'下限':'上限'):'实测数值'} value={value} onChange={e=>{let next=e.target.value;if(range){const parts=(form.measurements[size]?.[k]??'').split('-');parts[index]=next;next=`${parts[0]??''}-${parts[1]??''}`}change({measurements:{...form.measurements,[size]:{...form.measurements[size],[k]:next}}})}}/>{error&&<small id={id} className="measurement-error">{error.message}</small>}</div>
 }
 const selectedFields=form.sizeFields??['shoulder','chest']
 const sizeKind=form.sizeKind??'garment'
 const availableFields=(Object.keys(sizeFields) as SizeField[]).filter(k=>(k==='height'||k==='weight')===(sizeKind==='body_recommendation'))
 const manualFields=selectedFields.filter(k=>!sizeFields[k].platform)
 const copied=!!form.reuse,copyChecks=form.reuse?.checks??{priceStock:false,images:false,sizes:false}
 const [shop,setShop]=useState({shopName:'',mallId:'',templateName:'',groups:'',confirmed:false})
 const locked=disabled||working
 useEffect(()=>{request('entry').then(async data=>{setSettings(data.settings);setDefaults(data.defaults);setLoadedForm(data.currentForm);if(data.settings)setShop({...data.settings,groups:data.settings.groups.join('\n'),confirmed:false});if(!form.productCode){const next=await request('next-product-code',{});setForm(f=>f.productCode?f:{...f,id:next.id,productCode:next.productCode})}}).catch(e=>setMessage(e.message))},[request])
 useEffect(()=>{try{localStorage.setItem('mvp-entry-v1',JSON.stringify(form))}catch{setMessage('浏览器无法保存录入草稿，请勿刷新，先检查资料并载入')}},[form])
 useEffect(()=>{onDirty()},[]) // Restored input always needs fresh validation before platform writes.
 function change(patch:Partial<FormData>){setForm(f=>updateForm(f,patch));setMessage('');onDirty()}
 function changeProductCode(productCode:string){setForm(f=>({...f,productCode,rows:regenerateSkuCodes(f,productCode),confirmed:false}));setMessage('');onDirty()}
 async function act(fn:()=>Promise<void>){setWorking(true);setMessage('');setMessageFailed(false);try{await fn()}catch(e){setMessageFailed(true);setMessage(e instanceof Error?e.message:'操作失败')}finally{setWorking(false)}}
 async function upload(files:FileList|null,done:(p:Picture[])=>void){if(!files?.length)return;onDirty();await act(async()=>{const uploaded:Picture[]=[];for(const f of Array.from(files)){if(f.size>3_000_000)throw new Error(`${f.name} 超过 3MB，请压缩后选择`);const bitmap=await createImageBitmap(f);const {width,height}=bitmap;bitmap.close();if(width<=480||height<=480||(width!==height&&width*4!==height*3))throw new Error(`${f.name}：当前模板要求宽高均超过480像素，比例1:1或3:4`);const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('图片读取失败'));r.readAsDataURL(f)});uploaded.push(await request('assets',{name:f.name,data}))}done(uploaded)})}
 const field=(key:'title'|'brand'|'colors'|'sizes'|'referencePrice'|'discount',label:string,placeholder='')=><label>{label}<input data-field={key} value={form[key]} placeholder={placeholder} onChange={e=>change({[key]:e.target.value})} onBlur={()=>{if(key==='colors'||key==='sizes'){try{const rows=rebuildRows(form);if(JSON.stringify(rows)!==JSON.stringify(form.rows))change({rows})}catch(e){setMessage((e as Error).message)}}}}/></label>
 const imageLimitMessage=splitLabels(form.colors).length>10?'颜色最多10种，请减少颜色。':form.main.length>10||form.detail.length>10?'主图和详情图各最多10张，请移除多余图片。':''
 const pictures=(role:'main'|'detail',label:string)=><div><label>{label}<input type="file" accept="image/png,image/jpeg" multiple onChange={e=>{if(form[role].length+(e.target.files?.length??0)>10){setMessage(`${label}最多10张，请先移除多余图片`)}else void upload(e.target.files,p=>change({[role]:[...form[role],...p]}));e.target.value=''}}/></label><ol className="entry-pictures">{form[role].map((p,i)=><li key={p.path}>{p.preview&&<img className="entry-thumbnail" src={p.preview} alt={`${label} ${i+1}`}/>}<span>{i+1}. {p.name}</span><button type="button" disabled={i===0} onClick={()=>{const next=[...form[role]];[next[i-1],next[i]]=[next[i],next[i-1]];change({[role]:next})}}>上移</button><button type="button" onClick={()=>change({[role]:form[role].filter((_,n)=>n!==i)})}>移除</button></li>)}</ol></div>
 return <section className="live-card product-entry"><h2>1. 填写商品资料</h2><p>单款 T 恤 · 最多10种颜色、40个颜色尺码组合 · 同一颜色使用相同尺码集合 · 所有价格、库存、成分与尺寸请按实际填写。</p>
 <fieldset disabled={locked}>
 <details open={!form.title||form.sample===true} className="starter-guide"><summary>首次使用：完整初始版与操作指引</summary><p>不知道从哪里开始时，载入一份完整示例，先看各项怎么填，再换成自己的真实商品资料。包含全部当前必填属性、2种颜色×3个尺码、6行价格库存、图片及两种尺码表的数据。</p><button type="button" onClick={()=>void act(async()=>{const identity=await request('next-product-code',{});const images=await request('test-assets',{});replaceForm(starterProduct(identity,images));setShowIssues(false);setMessage('完整初始版已载入。当前价格、库存、属性、尺寸和图片均为演示资料；真实使用前逐项替换。原有录入可用顶部撤销恢复。')})}>载入完整初始示例</button><p>该按钮会替换当前录入表单，可撤销；不会改动已保存模板、店铺配置或商家页面。</p><ol><li><button type="button" onClick={()=>focusIssue('shop')}>先设置自己的店铺和运费</button>：这两项不能使用虚构示例。</li><li><button type="button" onClick={()=>focusIssue('title')}>修改标题、品牌和实物属性</button>：示例给出了填写格式，面料成分按真实标签填写。</li><li><button type="button" onClick={()=>focusIssue('colors')}>核实颜色、尺码和价格库存</button>：可逐格修改，也可整表粘贴。</li><li><button type="button" onClick={()=>focusIssue('measurements')}>核实实测尺码表</button>：切换身高体重表型可查看区间示例；这些建议值仅用于演示。</li><li><button type="button" onClick={()=>focusIssue('images')}>替换商品图片</button>：占位图标有测试说明，两种颜色共用测试图，不代表实物。</li><li>点击“检查全部资料”，修正问题并核实确认，再“检查资料并载入”。准备好商家编辑页后点击“填写并核对”；发布由你在平台手动操作。</li></ol><p>理解后可把自己的真实资料另存为商品模板，下次直接选择复用。</p></details>
 {form.sample&&<div role="note" className="reuse-warning"><strong>当前资料源于初始示例</strong><p>价格、库存、材质、尺寸与图片不是你的商品事实，不可直接用于销售。此标记会随复制和模板保存保留，提醒核实来源。</p></div>}
{undoForm&&<button type="button" onClick={()=>{setForm({...undoForm,confirmed:false});setUndoForm(null);onDirty();setMessage('已撤销上次套用或替换，恢复此前表单，请重新确认。')}}>撤销上次套用 / 替换</button>}{deleteTarget&&<div className="reuse-warning"><p>删除模板「{deleteTarget.name}」？当前商品及图片文件会保留。</p><button type="button" onClick={()=>void act(async()=>{const target=deleteTarget;const d=await request('delete-template',target);if(target.kind==='product'){setProductTemplates(d.templates);if(productTemplateId===target.id){setProductTemplateId('');setProductTemplateTitle('')}}else{setTemplates(d.templates);if(templateId===target.id){setTemplateId('');setTemplateName('')}}setDeleteTarget(null);setMessage('模板已删除，当前商品和图片未受影响。')})}>确认删除此模板</button><button type="button" onClick={()=>setDeleteTarget(null)}>取消</button></div>}<div className="live-actions"><button type="button" onClick={()=>void act(async()=>{const next=await request('next-product-code',{});replaceForm({...blankForm(next.id),productCode:next.productCode});setMessage('已新建空白商品并生成款式编号。')})}>新建空白商品</button><button type="button" disabled={!loadedForm} onClick={()=>void act(async()=>{if(!loadedForm)throw new Error('还没有可以复制的已载入商品');const next=await request('next-product-code',{});replaceForm(copyAsNewProduct(loadedForm,next));setMessage('已复制全部商品资料并生成新款式编号。请修改差异并重新确认复用内容。')})}>复制上一款全部资料</button><button type="button" disabled={!defaults} onClick={()=>{if(defaults){change({brand:defaults.brand,attributes:{...defaults.attributes}});setMessage('已复用品牌和属性，请按新商品实物核实。')}}}>只复用品牌与属性</button><button type="button" onClick={()=>void act(async()=>{const d=await request('entry');setSettings(d.settings);setDefaults(d.defaults);setLoadedForm(d.currentForm);setMessage('已更新店铺配置与可复用资料')})}>刷新常用配置</button><button type="button" disabled={!loadedForm} onClick={()=>{if(loadedForm){replaceForm(structuredClone(loadedForm));setMessage('已恢复当前商品全部资料并保留原款式编号。修改后请重新确认载入。')}}}>继续编辑当前商品</button></div>
 <details open><summary>商品模板：保存当前资料，选择模板复用</summary><p>可以保存多个模板，包含当前表单的商品资料、价格库存、图片和完整尺码表；未填完也能保存。套用会替换当前表单，生成新货号和规格编码；店铺和运费模板继续使用当前全局配置。</p><div className="entry-fields"><label>选择商品模板<select value={productTemplateId} onChange={e=>{setProductTemplateId(e.target.value);setProductTemplateTitle(productTemplates.find(t=>t.id===e.target.value)?.title??'')}}><option value="">请选择模板</option>{productTemplates.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>模板标题（与商品标题分别保存）<input maxLength={80} value={productTemplateTitle} placeholder="例如：秋款长袖基础款" onChange={e=>setProductTemplateTitle(e.target.value)}/></label></div><div className="live-actions"><button type="button" disabled={!productTemplateId} onClick={()=>void act(async()=>{const t=productTemplates.find(t=>t.id===productTemplateId);if(!t)throw new Error('请选择模板');const next=await request('next-product-code',{});const applied=applyProductTemplate(t.form,next);if(applied.form.reuse)applied.form.reuse.sourceTitle=t.title;replaceForm(applied.form);setMessage(`已套用「${t.title}」，请修改差异并重新确认复用资料。${applied.warning}`)})}>套用为新商品</button><button type="button" disabled={!productTemplateTitle.trim()} onClick={()=>void act(async()=>{const d=await request('product-templates',{title:productTemplateTitle,form});setProductTemplates(d.templates);setProductTemplateId(d.id);setMessage('当前表单已另存为新模板。')})}>另存为新模板</button><button type="button" disabled={!productTemplateId||!productTemplateTitle.trim()} onClick={()=>void act(async()=>{const d=await request('product-templates',{id:productTemplateId,title:productTemplateTitle,form});setProductTemplates(d.templates);setMessage('所选模板已用当前表单更新，其他模板保持原样。')})}>用当前资料更新所选模板</button><button type="button" onClick={()=>void act(async()=>{const d=await request('product-templates');setProductTemplates(d.templates);setMessage('商品模板列表已刷新。')})}>刷新商品模板</button><button type="button" disabled={!productTemplateId} onClick={()=>setDeleteTarget({kind:'product',id:productTemplateId,name:productTemplates.find(t=>t.id===productTemplateId)?.title??''})}>删除所选商品模板</button></div></details>
 {settings?<details><summary>目标店铺：{settings.shopName}（{settings.mallId}）· 查看运费配置</summary><p>{settings.templateName}</p><ul>{settings.groups.map(g=><li key={g}>{g}</li>)}</ul><p>配置仅为输入值，执行时还会核对实际店铺和运费规则。</p></details>:<p className="live-warning">请先完成下面的店铺设置，仅需配置一次。</p>}
 <details data-field="shop"><summary>首次设置 / 修改店铺与运费</summary><div className="entry-fields">{([['shopName','店铺名称'],['mallId','店铺编号'],['templateName','现有运费模板名称']] as const).map(([key,label])=><label key={key}>{label}<input value={shop[key]} onChange={e=>{setShop(s=>({...s,[key]:e.target.value,confirmed:false}));onDirty()}}/></label>)}</div><label>运费地区规则（从平台模板复制，每个分组一行）<textarea value={shop.groups} onChange={e=>{setShop(s=>({...s,groups:e.target.value,confirmed:false}));onDirty()}}/></label><p>当前支持已有的“其他运费模板”。需包括包邮、买家付运费、不配送等实际存在的分组及收费规则；不创建或修改平台模板。</p><label className="entry-check"><input type="checkbox" checked={shop.confirmed} onChange={e=>setShop(s=>({...s,confirmed:e.target.checked}))}/>我已核实以上店铺及运费规则</label><button type="button" disabled={!shop.confirmed} onClick={()=>void act(async()=>{await request('settings',shop);const d=await request('entry');setSettings(d.settings);onDirty();setMessage('店铺设置已保存。请重新检查商品资料并载入。')})}>保存店铺设置</button></details>
 {copied&&<div className="reuse-warning"><strong>{form.reuse?.sourceTitle?`本商品复用模板：${form.reuse.sourceTitle}`:'本商品复制自上一款'}</strong><p>已复用标题、属性、颜色、尺码、尺码表、价格库存、图片、物流和服务设置。系统已生成新的款式编号和规格编码，并清除平台商品、草稿、上传回执和审核关联。</p>{([['priceStock','价格与库存'],['images','商品图片'],['sizes','颜色、尺码及尺码表']] as const).map(([key,label])=><label className="entry-check" key={key}><input type="checkbox" checked={copyChecks[key]} onChange={e=>(()=>{setForm(f=>setReuseCheck(f,key,e.target.checked));onDirty()})()}/>我已按新商品重新核实{label}</label>)}</div>}
 <div className="entry-fields"><label>商品货号（款式编号，系统已生成）<div className="entry-inline"><input data-field="productCode" value={form.productCode} onChange={e=>changeProductCode(e.target.value)}/><button type="button" onClick={()=>void act(async()=>{const next=await request('next-product-code',{});changeProductCode(next.productCode)})}>重新生成</button></div><small>用于管理整款衣服，不是拼多多商品 ID；有供应商货号时可以替换。</small></label>{field('title','商品标题')}{field('brand','品牌','无品牌时填写平台对应选项')}</div>
 <details open><summary>商品属性（可复用上次属性，请逐项核实）</summary><div className="entry-fields">{Object.entries(attributeLabels).map(([k,label])=><label key={k}>{label}<input data-field={'attributes.'+k} list={'attribute-'+k} value={form.attributes[k]??''} onChange={e=>{setForm(f=>changeAttribute(f,k,e.target.value));onDirty()}}/><datalist id={'attribute-'+k}>{attributeChoices(form.attributes,k).map(v=><option key={v} value={v}/>)}</datalist><small>{attributeChoices(form.attributes,k).length?'可输入筛选历史候选，也可填写平台新选项。':'暂无该条件的可靠候选，请填写平台原文。'}</small></label>)}</div><p className="live-hint">{attributeCatalog.notice} 修改面料俗称会清空材质和成分选项，修改主风格会清空风格，请重新选择。特殊资质、额外尺寸及未支持字段在商家页面人工补充。</p></details>
 <h3>颜色、尺码及价格库存</h3><p className="live-hint">SKU 是 Stock Keeping Unit（库存管理单位），在这里就是一种“颜色＋尺码”组合。规格编码由系统自动生成，用户无需填写。修改颜色或尺码后离开输入框，规格表自动更新；新增组合需填写价格库存。MVP 保持每种颜色使用相同尺码集合。</p><div className="entry-fields">{field('colors','颜色（逗号分隔）','白色,黑色')}{field('sizes','尺码（逗号分隔）','S,M,L')}</div><button type="button" onClick={()=>{try{change({rows:rebuildRows(form)})}catch(e){setMessage((e as Error).message)}}}>生成 / 更新颜色尺码规格</button>
 <TablePaste kind="prices" form={form} onApply={replaceForm}/>
 {form.rows.length>0&&<div className="entry-scroll"><table><thead><tr><th>颜色 / 尺码</th><th>拼单价（元）</th><th>单买价（元）</th><th>库存</th><th>启用</th></tr></thead><tbody>{form.rows.map((r,i)=><tr data-field={`row:${r.color}:${r.size}`} key={JSON.stringify([r.color,r.size])}><td>{r.color} / {r.size}</td>{(['groupPrice','singlePrice','stock'] as const).map(k=><td key={k}><input aria-label={`${r.color} ${r.size} ${k}`} value={r[k]} onChange={e=>change({rows:form.rows.map((v,n)=>n===i?{...v,[k]:e.target.value}:v)})}/></td>)}<td><input aria-label={`${r.color} ${r.size} 启用`} type="checkbox" checked={r.enabled} onChange={e=>change({rows:form.rows.map((v,n)=>n===i?{...v,enabled:e.target.checked}:v)})}/></td></tr>)}</tbody></table></div>}
 <p className="live-hint">库存必须逐行明确填写。停用规格的库存须为 0，至少保留一个启用规格。</p>
 <div className="entry-fields">{field('referencePrice','商品参考价（元）')}{field('discount','满 2 件折扣','5.0～9.9')}</div><p className="live-hint">当前执行模板要求参考价高于全部单买价，并设置满 2 件折扣。若商品不适用此促销，请使用平台手动填写；系统不会默认添加折扣。</p>
 <div data-field="measurements"><h3>尺码表与选码建议</h3></div><TablePaste kind="sizes" form={form} onApply={replaceForm}/><label>模板类型<select value={sizeKind} onChange={e=>{const kind=e.target.value as SizeKind;setForm(f=>switchSizeKind(f,kind));onDirty()}}><option value="garment">成衣实测尺寸</option><option value="body_recommendation">身高体重选码建议</option></select></label>
 <p>成衣尺寸按实测录入；身高体重建议按供应商资料或已确认的试穿结果录入，不由系统推算。身高单位 cm，体重单位 kg（不是斤），最多一位小数。模板按尺码名称匹配；没有匹配的尺码留空，不推算尺寸。</p>
 <div className="entry-fields">{availableFields.map(k=><label className="entry-check" key={k}><input type="checkbox" checked={selectedFields.includes(k)} onChange={e=>change({sizeFields:e.target.checked?[...selectedFields,k]:selectedFields.filter(f=>f!==k),rangeFields:(form.rangeFields??[]).filter(f=>e.target.checked||f!==k)})}/>{sizeFields[k].label}{!sizeFields[k].platform?'（人工补充）':''}</label>)}</div>
 {manualFields.length>0&&<p className="live-warning">{manualFields.map(k=>sizeFields[k].label).join('、')}会保存在本工作台并随商品复用，当前平台执行器不自动填写。请在商家页面或详情图中人工补充；仍需至少选择一个支持自动填写的字段。</p>}
 <div className="entry-fields"><label>已保存的尺码模板<select value={templateId} onChange={e=>{setTemplateId(e.target.value);setTemplateName(templates.find(t=>t.id===e.target.value)?.name??'')}}><option value="">选择模板</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button type="button" disabled={!templateId} onClick={()=>{const t=templates.find(t=>t.id===templateId);if(t){replaceForm(applySizeTemplate(form,t));setMessage('已按商品尺码匹配模板，请核实实测数据；未匹配尺码需补填。')}}}>应用模板实测数据</button><label>尺码模板名称<input value={templateName} maxLength={60} onChange={e=>setTemplateName(e.target.value)}/></label><button type="button" disabled={!templateName.trim()} onClick={()=>void act(()=>saveSizeTemplate())}>另存为尺码模板</button><button type="button" disabled={!templateId||!templateName.trim()} onClick={()=>void act(()=>saveSizeTemplate(true))}>更新所选尺码模板</button><button type="button" disabled={!templateId} onClick={()=>setDeleteTarget({kind:'size',id:templateId,name:templates.find(t=>t.id===templateId)?.name??''})}>删除所选尺码模板</button><button type="button" onClick={()=>void act(async()=>{const d=await request('size-templates');setTemplates(d.templates);setMessage('尺码模板已刷新。')})}>刷新尺码模板</button></div>
 <div className="entry-scroll"><table><thead><tr><th>尺码</th>{selectedFields.map(k=><th key={k}>{sizeFields[k].label}（{sizeUnit(k)}）<label><input type="checkbox" checked={form.rangeFields?.includes(k)??false} onChange={e=>change({rangeFields:e.target.checked?[...(form.rangeFields??[]),k]:(form.rangeFields??[]).filter(f=>f!==k)})}/>区间值</label></th>)}</tr></thead><tbody>{splitLabels(form.sizes).map(size=><tr key={size}><td>{size}</td>{selectedFields.map(k=><td key={k}>{form.rangeFields?.includes(k)?<>{measurementInput(size,k,'min')}{measurementInput(size,k,'max')}</>:measurementInput(size,k)}</td>)}</tr>)}</tbody></table></div>

 {imageLimitMessage&&<p role="alert" className="live-warning">{imageLimitMessage}</p>}<h3 data-field="images" tabIndex={-1}>商品图片</h3><p>直接选择自己的 JPG / PNG 图片，不需要进入隐藏目录。主图和详情图各最多10张，颜色规格图每种颜色1张、最多10种颜色。单张不超过 3MB，宽高均超过480像素，比例1:1或3:4（当前模板限制）。</p><button type="button" onClick={()=>void act(async()=>{const d=await request('test-assets',{});change({main:d.main,detail:d.detail,skuImages:Object.fromEntries(splitLabels(form.colors).map(color=>[color,d.sku]))});setMessage(d.warning)})}>载入测试图片（仅测试草稿）</button>{pictures('main','主图（首张为封面）')}{pictures('detail','详情图')}
 <div className="entry-fields">{splitLabels(form.colors).map(color=><div key={color}><label>{color} 颜色规格图<input data-field={`skuImage:${color}`} aria-label={`选择${color}颜色规格图`} type="file" accept="image/png,image/jpeg" onChange={e=>{void upload(e.target.files,p=>change({skuImages:{...form.skuImages,[color]:p[0]}}));e.target.value=''}}/></label><button type="button" onClick={()=>focusIssue(`skuImage:${color}`)}>{form.skuImages[color]?'替换':'补充'}{color}图片</button>{form.skuImages[color]?.preview&&<img className="entry-thumbnail" src={form.skuImages[color].preview} alt={`${color}颜色规格图`} onLoad={e=>{e.currentTarget.style.display=''}} onError={e=>{e.currentTarget.style.display='none';setMessage(`${color}图片无法预览，请重新选择图片。`)}}/>}<small>{form.skuImages[color]?.name??'尚未选择'}</small>{form.skuImages[color]&&<button type="button" onClick={()=>{const images={...form.skuImages};delete images[color];change({skuImages:images})}}>移除该颜色图片</button>}</div>)}</div>
 <h3>发货与服务</h3><label>发货时效<select data-field="shipping" value={form.shipping} onChange={e=>change({shipping:e.target.value})}><option value="48h_handover">48 小时内发货及揽收</option><option value="24h_handover">24 小时内发货及揽收</option></select></label><p>固定模板：普通商品、非二手、非定制、非预售、2 人拼单、支付成功减库存、7 天无理由退货。与实际不符时请改用平台手工操作。</p>
 <label className="entry-check"><input type="checkbox" checked={form.nearbySameDay} onChange={e=>change({nearbySameDay:e.target.checked})}/>周边区域当天发货及揽收</label><label className="entry-check"><input type="checkbox" checked={form.authenticityPromise} onChange={e=>change({authenticityPromise:e.target.checked})}/>假一赔十</label>
 <section aria-label="资料检查"><button type="button" onClick={()=>{setShowIssues(true);setMessage('')}}>检查全部资料（无需先勾选确认）</button>{showIssues&&(issues.length?<><p>发现{issues.length}项问题，请按列表修改：</p><ul>{issues.map((issue,i)=><li key={i}><button type="button" onClick={()=>focusIssue(issue.field)}>{issue.message}</button></li>)}</ul></>:<p>本地输入检查通过，请核实后勾选确认并载入；平台选项和文件内容仍需后续校验。</p>)}</section>
 <label data-field="confirmation" className="entry-check"><input type="checkbox" disabled={!reuseConfirmed(form)} checked={form.confirmed} onChange={e=>{setForm(f=>({...f,confirmed:e.target.checked}));onDirty()}}/>我已核对商品资料、图片、价格库存和以上店铺/服务设置；测试资料仅用于测试草稿。</label>
 <button className="live-primary" type="button" disabled={!settings||!form.confirmed||!reuseConfirmed(form)||!!imageLimitMessage} onClick={()=>void act(async()=>{setShowIssues(true);if(collectFormIssues(form).length)throw new Error('请先修正资料检查列表中的问题');try{await request('entry',{form})}catch(e){throw new Error('商品资料未载入，无法执行当前资料的填表。'+(e instanceof Error?e.message:'请重试'))}setDefaults({brand:form.brand,attributes:{...form.attributes}});setLoadedForm({...structuredClone(form),confirmed:false});onLoaded();setMessage('资料已校验并载入。请准备目标编辑页，再点击“填写并核对”。')})}>检查资料并载入</button></fieldset>
 {message&&<p role={messageFailed?'alert':'status'} className={messageFailed?'live-error':'live-warning'}>{messageFailed&&<strong>本次操作失败：</strong>}{message}</p>}
 </section>
}
